import type { MembershipRole } from "@prisma/client";
import { TenantAccessError } from "@/lib/errors";

export const PERMISSIONS = {
  BLOG_VIEW: "BLOG_VIEW",
  BLOG_CREATE: "BLOG_CREATE",
  BLOG_UPDATE: "BLOG_UPDATE",
  BLOG_DELETE: "BLOG_DELETE",

  PAGE_VIEW: "PAGE_VIEW",
  PAGE_CREATE: "PAGE_CREATE",
  PAGE_UPDATE: "PAGE_UPDATE",
  PAGE_DELETE: "PAGE_DELETE",

  PROJECT_VIEW: "PROJECT_VIEW",
  PROJECT_CREATE: "PROJECT_CREATE",
  PROJECT_UPDATE: "PROJECT_UPDATE",
  PROJECT_DELETE: "PROJECT_DELETE",

  CAREER_VIEW: "CAREER_VIEW",
  CAREER_CREATE: "CAREER_CREATE",
  CAREER_UPDATE: "CAREER_UPDATE",
  CAREER_DELETE: "CAREER_DELETE",

  INQUIRY_VIEW: "INQUIRY_VIEW",

  MEDIA_VIEW: "MEDIA_VIEW",
  MEDIA_CREATE: "MEDIA_CREATE",
  MEDIA_DELETE: "MEDIA_DELETE",

  USER_VIEW: "USER_VIEW",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",

  SETTINGS_VIEW: "SETTINGS_VIEW",
  SETTINGS_UPDATE: "SETTINGS_UPDATE",

  SEO_VIEW: "SEO_VIEW",
  SEO_UPDATE: "SEO_UPDATE",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ALL_PERMISSIONS = Object.values(PERMISSIONS) as Permission[];

const VIEW_ONLY = ALL_PERMISSIONS.filter((p) => p.endsWith("_VIEW"));

/**
 * Role -> permission matrix. TENANT_ADMIN has full control of its tenant.
 * The other roles are prepared per Phase 4 for future use but aren't yet
 * assignable from the admin UI in Phase 1.
 */
const ROLE_PERMISSIONS: Record<MembershipRole, Permission[]> = {
  TENANT_ADMIN: ALL_PERMISSIONS,
  MANAGER: ALL_PERMISSIONS.filter((p) => !p.startsWith("USER_") || p === "USER_VIEW"),
  EDITOR: [
    PERMISSIONS.BLOG_VIEW, PERMISSIONS.BLOG_CREATE, PERMISSIONS.BLOG_UPDATE, PERMISSIONS.BLOG_DELETE,
    PERMISSIONS.PAGE_VIEW, PERMISSIONS.PAGE_CREATE, PERMISSIONS.PAGE_UPDATE, PERMISSIONS.PAGE_DELETE,
    PERMISSIONS.PROJECT_VIEW, PERMISSIONS.PROJECT_CREATE, PERMISSIONS.PROJECT_UPDATE, PERMISSIONS.PROJECT_DELETE,
    PERMISSIONS.MEDIA_VIEW, PERMISSIONS.MEDIA_CREATE, PERMISSIONS.MEDIA_DELETE,
    PERMISSIONS.SEO_VIEW, PERMISSIONS.SEO_UPDATE,
  ],
  AUTHOR: [PERMISSIONS.BLOG_VIEW, PERMISSIONS.BLOG_CREATE, PERMISSIONS.BLOG_UPDATE, PERMISSIONS.MEDIA_VIEW, PERMISSIONS.MEDIA_CREATE],
  HR: [PERMISSIONS.CAREER_VIEW, PERMISSIONS.CAREER_CREATE, PERMISSIONS.CAREER_UPDATE, PERMISSIONS.CAREER_DELETE, PERMISSIONS.USER_VIEW],
  EMPLOYEE: VIEW_ONLY,
  VIEWER: VIEW_ONLY,
};

export function hasPermission(role: MembershipRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

export function assertPermission(role: MembershipRole, permission: Permission): void {
  if (!hasPermission(role, permission)) {
    throw new TenantAccessError(`Role ${role} lacks permission ${permission}`);
  }
}
